static/css/style.css

That's what bulma is using for the navbar

Change breakpoint in navbar style to 1024px

---

static/css/upload.css
static/js/upload.js
templates/upload.html

Add support for pasting data from clipboard

---

docker-entrypoint

Busybox doesn't support the other syntax

Fix syntax for stat command in docker-entrypoint

---

handlers/download.go
handlers/upload.go
store/sqlite/sqlite.go
types/types.go

Record content type of uploaded files

---

templates/file-index.html

vertical-align table cells on File-Table

Add is-vcentered class to the table cells

---

static/js/fileIndex.js

This is for consistency with other files that use the name fileId.

Rename picoId to fileId

---

static/js/fileIndex.js

I commented this out when debugging and accidentally merged it in.

Uncomment accidentally commented-out snippet

---

static/css/file-index.css

Animate row after delete

---

static/js/upload.js

Reverts mtlynch/picoshare#172
This failed to upload the full image data.

Revert "Add a timestamp to the generated name of pasted image data"

---

static/js/upload.js

Set the Content-Type of uploaded text properly

---

static/js/upload.js

Create a better filename for pasted images

---

store/sqlite/migrations.go
store/sqlite/migrations/001-create-entries-table.sql
store/sqlite/migrations/002-create-entries_data-table.sql
store/sqlite/sqlite.go

This gives us the flexibility to change the database and apply migrations in the future as the schema changes.

Create database tables through migrations

---

handlers/upload.go

Increase max filename size to 255 characters

---

e2e/cypress/integration/guest_links_spec.js
handlers/guest_links.go
handlers/guest_links_test.go
handlers/routes.go
handlers/upload.go
handlers/upload_test.go
handlers/views.go
static/css/guest-link-index.css
static/js/controllers/guestLinks.js
static/js/controllers/upload.js
static/js/guestLinkCreate.js
static/js/guestLinkIndex.js
static/js/upload.js
store/sqlite/migrations/003-create-guest_links-and-modify-entries.sql
store/sqlite/sqlite.go
store/store.go
templates/guest-link-create.html
templates/guest-link-inactive.html
templates/guest-link-index.html
templates/upload.html
types/guest_link.go
types/types.go

Add support for uploads through guest URLs

---

handlers/csp.go
handlers/routes.go

Enforce Content Security Policy

---

handlers/csp.go

Fix CSP header syntax

---

dev-scripts/run-go-tests
e2e/cypress/integration/upload_spec.js
handlers/parse/file_note.go
handlers/parse/filenote_test.go
handlers/upload.go
handlers/upload_test.go
handlers/views.go
static/css/file-index.css
static/css/upload.css
static/js/controllers/upload.js
static/js/upload.js
store/sqlite/migrations/004-add-entries-note.sql
store/sqlite/sqlite.go
templates/file-index.html
templates/upload.html
types/types.go

Add note to upload

---

garbagecollect/collect.go
store/sqlite/sqlite.go
store/store.go

Perform a SQLite VACUUM as part of garbage collection

---

garbagecollect/collect_test.go
handlers/delete_test.go
handlers/upload_test.go

strings.NewReader can do the same thing more cleanly.

Delete makeData functions

---

static/js/fileDelete.js
templates/file-delete.html

I'd prefer if it was all in one file, but Prettier can't format it if it's all one file.

Move JS for file delete to a separate file

---

dev-scripts/run-go-tests

Make it more compliant with bash style.

Refactor run-go-tests script

---

e2e/cypress/integration/upload_spec.js
handlers/views.go
static/js/upload.js
templates/upload.html

Allow a custom expiration time on upload screen

---

static/js/upload.js
templates/upload.html

The name is misleading and unnecessary.

Remove name from file input field

---

dev-scripts/run-go-tests
handlers/static.go
handlers/upload.go
store/sqlite/file/writer.go
store/sqlite/file/writer_test.go

Fix spots where we were ignoring the return error code for a function.
Adds errcheck to the build to make sure we don't miss any in the future.

Fix missing checks for error

---

static/js/controllers/files.js
static/js/upload.js
templates/upload.html

Show upload progress bar

---

handlers/parse/file_note.go
handlers/parse/file_note_test.go
handlers/parse/filename.go
handlers/parse/filename_test.go
handlers/upload_test.go
handlers/views.go

Clarify that len(s) on a string checks byte count not char count

---

cmd/picoshare/main.go
go.mod
go.sum
handlers/delete_test.go
handlers/guest_links_test.go
handlers/routes.go
handlers/server.go
handlers/settings_test.go
handlers/templates/pages/disk-usage.html
handlers/templates/partials/navbar.html
handlers/upload_test.go
handlers/views.go
space/checker.go

Add page for checking disk usage

---

handlers/csp.go

I think I just was implementing it wrong.
Fixes #249

Remove CSP workaround for style tag

---

cmd/picoshare/main.go

the server now can be terminated by Ctrl-C. solve this problem in this PR.

response to shutdown signals

---

dev-scripts/reset-db

It was preventing globbing from working

Remove quotes around database path in reset-db

---

e2e/upload.spec.ts
handlers/templates/pages/upload.html
playwright.config.ts

Fix default expiration option in Firefox

---

README.md

Improves documentation for environment variables that affect PicoShare's runtime behavior.

Add better documentation for runtime options

---

.circleci/config.yml

CircleCI supports them natively now:
https://github.com/microsoft/playwright/issues/18108

Stop uploading Playwright artifacts to Backblaze

---

handlers/static/js/lib/clipboard.js
handlers/templates/pages/upload.html

This will allow us to test the behavior with a JS unit testing framework.

Move sortClipboardItems to a separate file

---

handlers/guest_links.go
handlers/parse/guest_link.go
handlers/parse/guest_link_test.go

Move it to the parse package and add unit tests.
Resolves #329

Refactor parsing for guest link label

---

e2e/file-info.spec.ts
e2e/upload.spec.ts
handlers/routes.go
handlers/templates/custom-elements/upload-links.html
handlers/templates/pages/file-edit.html
handlers/templates/pages/file-index.html
handlers/templates/pages/file-info.html
handlers/upload.go
handlers/upload_test.go
handlers/views.go
picoshare/guest_link.go
picoshare/picoshare.go
store/sqlite/entries.go

Add an extra page to show detailed file information for each upload.

Add file info page

---

dev-scripts/run-go-tests

Fix go install so that it works under Nix

Fix go install

---

package-lock.json
package.json

We moved Playwright's package.json to a separate folder in efcc93feaa8e8317b665fe431149637a300e6c87

Delete unneeded playwright install from root package.json

---

.circleci/config.yml
dev-scripts/build-backend
docker-entrypoint
flake.nix

Upgrade to shellcheck 0.9.0

---

e2e/guest-links.spec.ts
e2e/helpers/db.js
store/sqlite/entries.go

Handle case when guest link is deleted

---

flake.nix

This reverts commit c56088eace2f7229b16f8d77395df4bc0501346b.
I realized it was easier to fix my system configuration.

Revert "Unset GOROOT in flake.nix (#505)"

---

.circleci/config.yml
dev-scripts/package-binaries

Compress release binaries with gzip

---

space/checkers/filesystem.go

On ARM systems, apparently blocksize is an int32 instead of an int64, so we need to manually convert it to an int64.

Fix compilation error on ARM systems

---

dev-scripts/git-hooks/pre-commit

Skip build-frontend in pre-commit

---

handlers/upload_test.go

It's slightly more obvious in a non-leap year.

Adjust 365-day expiration time test

---

handlers/guest_links.go
handlers/parse/expiration.go
handlers/parse/expiration_test.go
handlers/upload.go

Who could have anticipated that it would eventually be 2025?

Control time in expiration tests

---

garbagecollect/collect_test.go
handlers/delete_test.go
handlers/download_test.go
handlers/upload.go
handlers/upload_test.go
handlers/views.go
picoshare/file_size.go
picoshare/file_size_test.go
picoshare/picoshare.go
space/checkers/database.go
space/checkers/database_test.go
store/sqlite/entries.go
store/sqlite/entries_test.go

This ensures that a file size can never be zero or negative.

Switch to a FileSize type

---

handlers/views.go

Resolves https://github.com/mtlynch/picoshare/issues/641
Related PR: https://github.com/mtlynch/picoshare/pull/644
The above PR has largely addressed the corresponding issue, but there is one missing part. This PR completes the missing part.

Show expiration time in server's local time

---

handlers/templates/pages/system-information.html
handlers/views.go

Fix disk usage formatting on information page

---

store/sqlite/cleanup.go
store/sqlite/entries.go
store/sqlite/guest_links.go
store/sqlite/migrations.go

I always thought this happened automatically, but I guess it doesn't.

Add tx.Rollback for all transactions
