mtlynch/picoshare

handlers/upload.go, store/memory/memory.go, store/sqlite/sqlite.go, store/store.go, templates/file-index.html
If each entry knows its ID, we don't need to pass it in separately.
=> Refactor store.InsertEntry semantics

docs/fly.io.md
Otherwise, it prints a spurious success message when deploy fails
=> Chain together deploy command

handlers/views.go
html/template does proper escaping of values
=> Use html/template instead of text/template

garbagecollect/collect_test.go, handlers/delete_test.go, handlers/upload_test.go
There's a race condition documented in the mattn/gosqlite driver where multiple clients of the DB pool can get separate copies of the database and have distinct views. Using a shared cache works around this issue.
=> Change tests to use SQLite in-memory with a shared cache

garbagecollect/collect_test.go
The entry insertion doesn't actually read the size property of the metadata, so we can omit it when we insert data for the test.
=> Simplify garbage collection tests

garbagecollect/collect_test.go, handlers/delete_test.go, handlers/upload_test.go, store/sqlite_test/db.go
If unit tests all use the :memory: special name, the DB can persist across tests and taint results between tests. This ensures that each test case gets a unique database.
=> Add function for creating SQLite test DBs

docs/fly.io.md
They've changed the behavior so that encryption is default, so the --encrypted flag no longer works
=> Fix fly volumes create command

store/sqlite/sqlite.go
As of 417c03056ec47a7a1a9f60428bbbf393bb15f81e, the garbage collector purges expired files, so we don't have to check the expiration time in SQLite.
=> Remove sqlite checks for expiration

garbagecollect/collect_test.go, handlers/delete_test.go, handlers/upload_test.go, store/test_sqlite/db.go
This avoids naming conflicts when we want to write unit tests for a sqlite package.
=> Rename sqlite_test to test_sqlite

handlers/auth/shared_secret/shared_secret.go
This makes password checking resistant to timing attacks.
=> Use a constant-time string comparison for password checking

docker-entrypoint
Fixes a bug in docker-entrypoint where we weren't passing the correct -db flag to picoshare unless we were running with Litestream enabled.
=> Fix SQLite database path for non-Litestream scenarios

handlers/auth/shared_secret/shared_secret.go
We don't need to log every request without a cookie
=> Remove log message about missing shared secret cookie

garbagecollect/collect_test.go, handlers/views.go, static/js/upload.js, types/types.go
This is a naive way of solving https://github.com/mtlynch/picoshare/issues/92 by adding a "never" expire option by setting the data way into the future.
=> Adds a "never" expiration option

dev-scripts/enable-git-hooks
The ln command are broken under Apple Mac. The long form args are not available under.
=> Fix sym-link for Apple

static/js/controllers/upload.js
Otherwise, + character gets converted to a space when the server parses it, which causes expiration time parsing to fail.
Fixes #139
=> URL-encode expiration timestamp

static/js/fileIndex.js
The logic for finding the row was flimsy and we accidentally broke it in c1ce1b30a5d29f340597debd87769f6071484ef5.
=> Fix CSS for delete in file table

types/types.go
I meant for this to be 3000-01-01, but I accidentally formatted it as 3000-01-00, which ticks back to 2999-12-31, so let's just use that as the NeverExpire time.
Fixes #151
=> Fix types.NeverExpire to be 2999-12-31

go.mod, go.sum, handlers/auth/shared_secret/shared_secret.go, static/js/controllers/auth.js
We were previously storing the password in plaintext as a cookie. This was insecure, but fairly low risk because in order to compromise the key, an attacker would need to compromise the user's browser (beyond XSS, as it's an HttpOnly key).
Storing the secret in plaintext additionally had the problem of not properly encoding characters that are not allowed in HTTP cookies.
This change hashes passwords with PBKDF2 and stores the result as base64-encoded bytes.
Fixes #166
=> Use PBKDF2 to hash shared secret

static/js/upload.js
By default, images get the name image.png, so we're generating a better name.
Fixes #165
=> Add a timestamp to the generated name of pasted image data

handlers/upload.go, handlers/upload_test.go
Our unit tests weren't testing the upload method correctly, so even though we thought we were testing for empty uploads, we weren't really rejecting those requests.
This refactors the tests to fix the test bug and changes the upload POST behavior to reject uploads of empty files.
=> Disallow empty file uploads and refactor unit tests

dev-scripts/run-go-tests
It's otherwise too hard to find failures
=> Use less verbose test output by default

garbagecollect/collect_test.go, handlers/views.go, store/sqlite/sqlite.go, store/sqlite/sqlite_test.go, types/types.go
File sizes can be larger than 32-bits, so we should explicitly use a 64-bit int to store it.
=> Make file size type int64 instead of int

store/sqlite/migrations/.sqlfluffignore, store/sqlite/migrations/005-add-chunk-length-index.sql
Without an index, calling `LENGTH` on blob data reads all of the data into memory. When the database gets to > 1 GB in data, this can take 10+ seconds for simple queries, which is too slow.
Adding the index drops the latency down to a few milliseconds, so it's a fairly simple solution.
I originally thought we'd have to store a redundant copy of the file size (see #221), but the index implementation is much simpler and less bug-prone.
Fixes #220
=> Create an index for calculating file sizes quickly

docker-entrypoint
This facilitates debugging when things aren't working as expected.
=> Print Litetream bucket and endpoint in Docker

static/js/upload.js
Fixes an issue on Firefox where pasting text copied from a web browser would paste HTML-formatted text. This change sorts the various clipboard data formats and prefers text/plain over text/html.
Fixes #250
=> Prefer to paste plaintext strings

.prettierrc, templates/custom-elements/snackbar-notifications.html, templates/custom-elements/upload-link-box.html, templates/custom-elements/upload-links.html
There seems to be a bug in prettier-plugin-go-template that prevents it from formatting custom elements correctly when they contain Go template syntax, so we're tightening the matcher for Go templates to not match HTML custom elements.
See: https://github.com/NiklasPor/prettier-plugin-go-template/issues/84
=> Use stock Prettier to format custom elements

.prettierrc, package-lock.json, package.json
Related: #254
This is gated on the official release of [prettier-plugin-go-template](https://github.com/NiklasPor/prettier-plugin-go-template) 0.13.0
=> Remove workaround for prettier-plugin-go-template bug

.circleci/config.yml, store/sqlite/migrations/.sqlfluffignore
The bug is now fixed, so we don't need a workaround: https://github.com/sqlfluff/sqlfluff/issues/3237
=> Remove sqlfluff workaround

store/sqlite/file/reader.go
In #284, @danwilhelm spotted a mistake in the reader.go implementation where the populateBuffer reads not only the current chunk but all subsequent chunks in the file and then discards them. There was no reason for reading the remaining chunks as far as I remember, so I think this was just a simple oversight.
This change changes the SQL comparison from >= to =.
=> Fix a SQL mistake in file reader

store/sqlite/file/reader.go, store/sqlite/sqlite.go
None of them are actually necessary and can just execute immediately.
=> Remove unnecessary SQL prepared statements

handlers/upload.go
As @benbjohnson (#283) and @danwilhelm (#284) have found, using 32 << 20 (32 MiB) as the limit in ParseMultipartForm actually consumes significantly more than 32 MiB of RAM.
This changes the limit to 1 MiB so that we avoid consuming too much RAM on the system.
=> Use less RAM while parsing a multipart form

handlers/upload.go, handlers/upload_test.go
This refactors the code to ensure that we always call r.MultipartForm.RemoveAll after parsing a multipart request.
=> Free multipart resources after reading them

Dockerfile
In some contexts, we're evaluating with /bin/sh instead of /bin/bash, so we can't use the bash syntax
Related: eb82af099d328f1bcb47e6bce4105adcf3b9d72b
=> Switch back to single brackets in shell conditionals in Dockerfile

store/sqlite/file/reader.go
We're only reading one chunk at a time, so chunkIndex is a more accurate name.
=> Rename startChunk to chunkIndex

garbagecollect/collect.go, garbagecollect/collect_test.go, store/sqlite/sqlite.go
Changes addressing TODO comment in Collector: deletes expired entries more efficiently with single SQL statement instead of deleting them in for loop.
=> Delete expired entries in Purge

handlers/guest_links.go, handlers/parse/file_note.go, handlers/parse/file_note_test.go, handlers/parse/filename.go, handlers/parse/filename_test.go
len(s) gives you the byte count rather than the character count, so this fixes the mistake.
We don't apply this check to entry IDs because they can only be single-byte characters.
=> Count runes to validate user-controlled strings

handlers/guest_links.go, handlers/parse/file_note.go, handlers/parse/file_note_test.go, handlers/parse/filename.go, handlers/parse/filename_test.go
Based on feedback from others, I think the original `len` is the implementation we want, because we're just placing an arbitrary limit on the strings so they don't occupy too much storage space.
Reverts mtlynch/picoshare#328
=> Revert "Count runes to validate user-controlled strings"

cmd/picoshare/main.go, store/sqlite/sqlite.go, store/test_sqlite/db.go
Litestream has a set of SQLite pragmas it recommends, but we should only apply them when we're actually using Litestream. Otherwise, we should stick with the SQLite defaults.
Related: #341
=> Only apply Litestream pragmas when Litestream is enabled

static/js/upload.js
If the user pastes from clipboard and the clipboard data is available in multiple formats, we should prefer image formats ahead of other formats.
Fixes #350
=> Prefer image clipboard types to other data types

README.md
The README incorrectly said the default port was 4001, but it's actually 3001. This updates the README to match PicoShare's actual default behavior.
Fixes #358
=> Update README to reflect correct default port

Dockerfile
It can't be /app/picoshare because then it collides with the folder name.
=> Fix path to picoshare binary

modd.conf
Since they're now embedded in the server, we need to rebuild on changes to static files.
=> Reload live server on changes to static files

space/checker.go
We're accidentally finding the parent directory twice instead of just once from the DB path.
=> Remove directory traversal from space.Checker

handlers/csp.go
Reverts changes related to  aa0f0daaa7bfae35564d8f285f0ae462e823fd83
=> Revert workaround for CSP on Firefox

LICENSE
These were actually instructions to the license holder, not part of the license.
=> Trim parts of the AGPL license that shouldn't have been included

docker-entrypoint
follow [PR398](https://github.com/mtlynch/picoshare/pull/398)
i'm sorry for that i didn't take an eye on Docker entrypoint.
as [this answer](https://unix.stackexchange.com/questions/146756/forward-sigterm-to-child-in-bash/196053#196053) point out
>Bash does not forward signals like SIGTERM to processes it is currently waiting on. If you want to end your script by segueing into your server (allowing it to handle signals and anything else, as if you had started the server directly), you should use exec, which will replace the shell with the process being opened
so before this PR processes in container are
```
/bin/bash /app/docker-entrypoint -db /data/store.db  (won't forward signals to child
|
+---> /app/litestream replicate -exec /app/picoshare -db /data/store.db (will forward signals to …
```
=> docker-entrypoint: exec & allowing server to handle signals

playwright.config.ts
Otherwise the dev database could interfere with the e2e database.
=> Use a separate SQLite database during e2e tests

dev-scripts/reset-db
When I added another database in f35ff388c74f17042e7491cb9e3dee6d2aa9e23d, I forgot to update the reset DB pattern to match.
=> Broaden glob pattern for reset-db

.circleci/config.yml
Fix CircleCI config so that we upload artifacts even if the e2e tests fail
=> Always upload Playwright results to Backblaze

.circleci/config.yml
Forked PRs don't have access to environment variables, so the upload will fail.
=> Skip backblaze upload on forked PRs

handlers/download.go, handlers/download_test.go, picoshare/picoshare.go
Resolves #427 
If the client didn't specify the content type for a file at upload time, we can try to infer it based on the filename. This is helpful for files like mp4s or mp3s that modern browsers can play natively instead of relying on the user to download it and find a client player.
=> Infer content type when it wasn't specified at upload time

handlers/download_test.go
This moves the dummy data before the tests to make it easier to read top to bottom.
=> Refactor download_test.go

cmd/picoshare/main.go, handlers/delete_test.go, handlers/download_test.go, handlers/guest_links_test.go, handlers/server.go, handlers/settings_test.go, handlers/upload_test.go
It can't fail, so there's no point in returning an error type.
=> Remove error return type from handlers.New

handlers/download.go, handlers/download_test.go
curl specifies a Content-Type of application/octet-stream for mp3 and mp4 files, so this treats those the same as missing content type files and infers a better content type.
=> Infer mp3/mp4 content type when client specifies octet-stream

e2e/auth.spec.ts, e2e/guest-links.spec.ts, e2e/helpers/login.js, e2e/paste.spec.ts, e2e/settings.spec.ts, e2e/upload.spec.ts, handlers/templates/partials/navbar.html
Instead of using hrefs, IDs, or test IDs, we should use ARIA roles and text, as it's closer to how real users navigate the site.
=> Refactor e2e tests to click menu items by role

.circleci/config.yml, .eslintrc.js, .gitignore, .prettierignore, dev-scripts/run-e2e-tests, e2e/package-lock.json, e2e/package.json, e2e/playwright.config.ts
We want to install mocha in the other package.json file, and the two don't get along. mocha needs us to set type='module' and playwright needs us *not* to set type='module'.
=> Give playwright its own package.json

dev-scripts/package-binaries
Previously, it was releasing the folder name in addition to the binary. This fixes it so it just releases the binary by itself.
=> Exclude directory structure from binary packages

e2e/guest-links.spec.ts, e2e/paste.spec.ts, e2e/upload.spec.ts, handlers/templates/pages/file-index.html, handlers/templates/pages/guest-link-index.html
This changes the test ID attribute in HTML from test-data-id to data-testid, which matches Playwright's conventions (and seems to be more common among other apps).
=> Change HTML test ID attribute name to data-testid

e2e/guest-links.spec.ts, e2e/paste.spec.ts, e2e/upload.spec.ts, handlers/templates/pages/file-index.html, handlers/templates/pages/guest-link-index.html
The data-testid attributes are kind of a hack. We can more usefully exercise the UI in e2e tests by using role-based Playwright locators rather than having special test data IDs.
=> Delete data-testid attributes

.circleci/config.yml
We should do the packaging step on the master branch so that there are fewer steps that happen only on release.
=> Package releases on master

handlers/templates/custom-elements/upload-links.html
For default slots, we don't need to include the slot element, and in some cases, it messes up rendering.
=> Remove incorrect slot elements in upload-links

e2e/upload.spec.ts, handlers/templates/pages/file-delete.html, handlers/templates/pages/file-edit.html, handlers/templates/pages/file-index.html
Most of them were unused. In other cases, they were only being used in tests, and there are better element selectors.
=> Delete pico-purpose attributes

handlers/static.go
We accidentally broke caching for static files in #452 because the technique we were using to look up last modification times of files broke when we started embedding them in the binary.
As a workaround, we now use the last modification time based on the first time the static serving function is called.
Resolves #496
=> Fix cache headers for static files

handlers/download.go
This PR results in use of the more extensive stdlib mimetype derivation mechanism instead of the special cases for `.mp3` and `.mp4`.
=> Use the Go-builtin (more extensive) file extension -> mimetype mapping

handlers/delete_test.go, handlers/server.go, space/checker.go
It makes more sense for the client to specify the interface they need rather than for the space package to dictate the right interface to clients.
=> Simplify space package

cmd/picoshare/main.go, garbagecollect/collect.go, handlers/db_dev.go, handlers/db_prod.go, handlers/delete_test.go, handlers/download.go, handlers/download_test.go, handlers/guest_links_test.go, handlers/server.go, handlers/settings_test.go, handlers/store.go, handlers/upload_test.go, store/sqlite/cleanup.go, store/sqlite/downloads.go, store/sqlite/entries.go, store/sqlite/guest_links.go, store/sqlite/settings.go, store/sqlite/sqlite.go, store/store.go, store/test_sqlite/db.go
It makes more sense for the consuming packages to define the interface to the application data store. The SQLite implementation should just export what it exports, and the clients define interfaces over what they need.
=> Define app store interface in client packages

.dockerignore, .gitignore, dev-scripts/download-prod-db, dev-scripts/serve-docker
Use the .env convention, which is more widely used than whatever.env
=> Rename environment files

dev-scripts/download-prod-db
Don't rely on the .env file to export them.
=> Export environment variables from download-prod-db

handlers/upload_test.go
Resolves #298
This avoids the variable name from colliding with the package name.
=> Change var name from store to dataStore

.circleci/config.yml
Resolves #558 
I forgot to include the `PS_VERSION` Docker build arg when building the release binaries, which caused the version displayed in the web app to be empty. Adding the proper arg should fix the issue.
=> Store the PicoShare version number in the release binaries

e2e/download-history.spec.ts, e2e/upload.spec.ts, handlers/templates/pages/file-index.html, picoshare/picoshare.go, store/sqlite/entries.go, store/sqlite/entries_test.go
Fixes #494
I didn't change GetEntryMetadata, even though it was required by the description of the issue. Because download count for a single file is already implemented and used via downloads, err := s.getDB(r).GetEntryDownloads(id), len(downloads). But I can change GetEntryMetadata too if this approach (through one request to sql and left join) looks better
=> Display download count on file index

cmd/picoshare/main.go
as golang's http doc point out
```
ListenAndServe always returns a non-nil error. After Shutdown or Close
```
`log.Fatal(httpSrv.ListenAndServe())` will cause server exit immediately with code 1, without waiting 5s for graceful shutdown.
=> fix http server graceful shutdown

docker-entrypoint
Addresses #573 
Removing `-v` from the `litestream restore` command as it is now the default.
=> Remove litestream verbose flag

go.mod, go.sum
*...the title says it all.*
Updated `go-sqlite3` using `go get github.com/mattn/go-sqlite3@latest` to fix build issue on Alpine.
Fix #576
=> Update go-sqlite3 to v1.14.22

handlers/delete_test.go, handlers/download_test.go, handlers/guest_links_test.go, handlers/settings_test.go, handlers/upload_test.go
I noticed that there is a subtle issue in the test setup, which could potentially lead to false positive test results.
According to the [documentation of `httptest.ResponseRecorder` (see their example)](https://pkg.go.dev/net/http/httptest#ResponseRecorder), you are supposed to run the test assertions against the result object returned by `recorder.Result()`, rather than against the recorder object itself.
The recorder object basically tracks all interactions of the request handlers with the response. However, this may be different from what the HTTP server actually sends out to the client.
One such edge-case scenario is when you try to set response headers after having flushed out the response headers. In this case, any attempt to modify the headers via `res.Headers().Set()` will …
=> Assert against result object instead of recorder

handlers/views.go, picoshare/file_lifetime.go, picoshare/picoshare.go, store/sqlite/sqlite.go
It breaks encapsulation too much to just hand callers the underlying object.
=> Get rid of FileLifetime.Duration function

cmd/picoshare/main.go, handlers/clock.go, handlers/delete_test.go, handlers/download.go, handlers/download_test.go, handlers/guest_links.go, handlers/guest_links_test.go, handlers/server.go, handlers/settings_test.go, handlers/upload.go, handlers/upload_test.go, handlers/views.go
Checking the time through a clock interface rather than through time.Now allows us to mock out the time in tests where the time makes a difference such as #619
=> Add a clock interface to the server

handlers/upload_test.go
It feels more intuitive to me alongside the properties of the server rather than near the responses
=> Reorder currentTime in tests

handlers/upload.go, store/sqlite/entries_test.go, store/sqlite/file/writer.go, store/sqlite/file/writer_test.go, store/sqlite/sqlite.go, store/test_sqlite/db.go
It can't be negative anyway, so uint is better than int, and uint64 makes it work nicely with other values around file size that have to be uint64.
=> Make chunk size a uint64

store/sqlite/guest_links.go
For some reason, the mattn driver doesn't catch this violation of the FOREIGN KEY constraint, but ncruces does. The fix is to just switch up the order so that we delete the references before deleting the underlying data. It's in a transaction, so we shouldn't be able to end up with invalid data.
=> Delete references to guest link before deleting the link

store/sqlite/file/reader.go, store/sqlite/file/writer.go
It's only used in one function, so we should inline it there.
=> Inline the min function

store/sqlite/entries.go
This is to avoid violating FOREIGN KEY constraints, similar to 856240aa858be137ebc6effe828ab81881c8d71f
=> Delete references to entries before deleting entries

handlers/templates/custom-elements/expiration-picker.html
I don't think this will fix #641, but it gets rid of an unintentional time zone conversion and makes the code clearer.
=> Fix formatter in expiration picker

handlers/templates/pages/guest-link-index.html, handlers/views.go
It wasn't actually necessary as templates can call the regular function directly.
=> Delete isActive template function

handlers/guest_links_test.go, store/sqlite/guest_links.go
Since we've added the Clock interface, we can test guest link creation more rigorously.
=> Test guest link creation time

docs/deployment/fly.io.md
If we don't need interpolation, we shouldn't use double quotes.
=> Use single quotes in bash examples when we can

handlers/upload_test.go
This occurs before what we're going to call the PicoShare epoch of 2022-02-20
=> Replace test values of 2022-01-01

garbagecollect/collect_test.go
We're adding stricter validation to the DB soon, so this avoids breaking tests.
=> Define upload time in garbagecollect tests

handlers/delete_test.go
Now that we're checking constraints since e04eab580faa0757fa9a41aa5925557388e7e660, we should populate the times correctly.
=> Add times to delete test

e2e/guest-links.spec.ts
They're in separate contexts, so we don't need separate names
=> Simplify cookie variable names

store/sqlite/migrations/011-downloads-id-as-text.sql, store/sqlite/migrations/012-fix-entries_data-foreign-key.sql
The existing migration failed to account for orphaned rows in the download table and entries_data table that referred to files that had been deleted.
This fixes the migration so that we only migrate over rows that are not orphaned.
Fixes #705
=> Fix foreign key reference in database migrations
